-- data/*.json から生成。手動編集しないでください。
PRAGMA foreign_keys = ON;

INSERT INTO campaigns (id, name, starts_on, ends_on, source_url, published) VALUES ('chiikawa-kurasushi-2026-summer', 'ちいかわ × くら寿司 コラボキャンペーン', '2026-08-21', '2026-09-30', 'https://www.kurasushi.co.jp/author/008384.html', 1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, starts_on=excluded.starts_on, ends_on=excluded.ends_on, source_url=excluded.source_url, published=excluded.published;
INSERT INTO prize_categories (id, campaign_id, name, sort_order, active) VALUES ('chiikawa-2026-figure', 'chiikawa-kurasushi-2026-summer', 'フィギュア', 1, 1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, sort_order=excluded.sort_order, active=excluded.active;
INSERT INTO prize_categories (id, campaign_id, name, sort_order, active) VALUES ('chiikawa-2026-can-badge', 'chiikawa-kurasushi-2026-summer', '缶バッジ', 2, 1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, sort_order=excluded.sort_order, active=excluded.active;
INSERT INTO prize_categories (id, campaign_id, name, sort_order, active) VALUES ('chiikawa-2026-acrylic-magnet', 'chiikawa-kurasushi-2026-summer', 'アクリルマグネット', 3, 1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, sort_order=excluded.sort_order, active=excluded.active;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-664', '新宿靖国通り店', '東京都', '新宿区', '東京都新宿区新宿5-17-13 オリエンタルウェーブビル5F', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/664', 1, '新宿靖国通り店東京都新宿区東京都新宿区新宿5-17-13おりえんたるうぇーぶびる5f') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-662', 'アトレ取手店', '茨城県', '取手市', '茨城県取手市中央町2-5 アトレ取手5F', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/662', 1, 'あとれ取手店茨城県取手市茨城県取手市中央町2-5あとれ取手5f') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-14', '柴田本通店', '愛知県', '名古屋市南区', '愛知県名古屋市南区柴田本通1-3-2', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/14', 1, '柴田本通店愛知県名古屋市南区愛知県名古屋市南区柴田本通1-3-2') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-254', '富山天正寺店', '富山県', '富山市', '富山県富山市天正寺1053', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/254', 1, '富山天正寺店富山県富山市富山県富山市天正寺1053') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-143', '金沢入江店', '石川県', '金沢市', '石川県金沢市入江3-15', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/143', 1, '金沢入江店石川県金沢市石川県金沢市入江3-15') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-104', '堅田店', '滋賀県', '大津市', '滋賀県大津市今堅田2-39-20', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/104', 1, '堅田店滋賀県大津市滋賀県大津市今堅田2-39-20') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-547', 'なんば日本橋店', '大阪府', '大阪市中央区', '大阪府大阪市中央区難波千日前15-15 BRAVE難波4F', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/547', 1, 'なんば日本橋店大阪府大阪市中央区大阪府大阪市中央区難波千日前15-15brave難波4f') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-273', 'アイモール高砂店', '兵庫県', '高砂市', '兵庫県高砂市米田町島25-C-1（アイモール高砂内）', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/273', 1, 'あいもーる高砂店兵庫県高砂市兵庫県高砂市米田町島25-c-1(あいもーる高砂内)') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-537', '岡山北店', '岡山県', '岡山市北区', '岡山県岡山市北区伊島北町4-7', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/537', 1, '岡山北店岡山県岡山市北区岡山県岡山市北区伊島北町4-7') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-489', '広島五日市店', '広島県', '広島市佐伯区', '広島県広島市佐伯区五日市中央7-25-12', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/489', 1, '広島五日市店広島県広島市佐伯区広島県広島市佐伯区五日市中央7-25-12') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-518', '福岡高木店', '福岡県', '福岡市南区', '福岡県福岡市南区高木1-9-9', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/518', 1, '福岡高木店福岡県福岡市南区福岡県福岡市南区高木1-9-9') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-661', '長崎大波止店', '長崎県', '長崎市', '長崎県長崎市元船町10-5 2F', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/661', 1, '長崎大波止店長崎県長崎市長崎県長崎市元船町10-52f') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;
INSERT INTO stores (id, name, prefecture, city, address, latitude, longitude, official_url, active, search_text) VALUES ('kura-487', 'ABLOうるま店', '沖縄県', 'うるま市', '沖縄県うるま市字豊原9-1', NULL, NULL, 'https://shop.kurasushi.co.jp/detail/487', 1, 'abloうるま店沖縄県うるま市沖縄県うるま市字豊原9-1') ON CONFLICT(id) DO UPDATE SET name=excluded.name, prefecture=excluded.prefecture, city=excluded.city, address=excluded.address, latitude=excluded.latitude, longitude=excluded.longitude, official_url=excluded.official_url, active=excluded.active, search_text=excluded.search_text;

INSERT OR IGNORE INTO store_campaign_stats (store_id, campaign_id) SELECT stores.id, campaigns.id FROM stores CROSS JOIN campaigns;
PRAGMA optimize;
